import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "en_label_inventory.md"


def read_labels():
    labels = []
    for line in INVENTORY.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\d+\.\s+(.*)$", line.strip())
        if m:
            labels.append(m.group(1))
    seen = set()
    ordered = []
    for label in labels:
        if label not in seen:
            seen.add(label)
            ordered.append(label)
    extras = [
        "Language:",
        "Executive Analytics",
        "Job Order",
        "Created",
        "Resolution Min",
        "SLA Breach Min",
        "HotelChain",
        "HotelCode",
        "Hotelname",
        "Module",
        "CountryCode",
        "Chart Formula",
    ]
    for label in extras:
        if label not in seen:
            seen.add(label)
            ordered.append(label)
    return ordered


def translate(text, rules):
    out = text
    for src, dst in sorted(rules, key=lambda p: len(p[0]), reverse=True):
        out = out.replace(src, dst)
    return out


BASE_RULES = []

RULES = {
    "en": BASE_RULES,
    "es": [
        ("Corporate Dashboard", "Panel corporativo"),
        ("OPS Dashboard", "Panel OPS"),
        ("GM Dashboard", "Panel GM"),
        ("Master Dashboard", "panel maestro"),
        ("Dashboard", "panel"),
        ("Switch:", "Cambiar:"),
        ("Filters", "Filtros"),
        ("From:", "Desde:"),
        ("To:", "Hasta:"),
        ("Apply", "Aplicar"),
        ("Reset", "Restablecer"),
        ("Toggle Dark/Light", "Oscuro/Claro"),
        ("Language:", "Idioma:"),
        ("Executive Analytics", "Analítica ejecutiva"),
        ("Job Order", "Orden de trabajo"),
        ("Created", "Creado"),
        ("Resolution Min", "Min. resolución"),
        ("SLA Breach Min", "Min. incumplimiento SLA"),
        ("Export (PDF)", "Exportar (PDF)"),
        ("Loading dashboard...", "Cargando panel..."),
        ("Core Dashboard Charts", "Gráficos principales del panel"),
        ("KPI & Chart Dictionary", "Diccionario de KPI y gráficos"),
        ("Top 20 JO", "Top 20 JO"),
        ("All Hotels", "Todos los hoteles"),
        ("All JO records", "Todos los registros de JO"),
        ("NOTE", "NOTA"),
        ("FORMULA", "FÓRMULA"),
        ("by week", "por semana"),
        ("by Hotel", "por hotel"),
        ("Service Category", "Categoría de servicio"),
        ("Service Items", "ítems de servicio"),
        ("Service Item", "ítem de servicio"),
        ("Drilldown", "desglose"),
        ("Completion Rate", "Tasa de finalización"),
        ("SLA Compliance", "Cumplimiento SLA"),
        ("Timeout Rate", "Tasa de tiempo excedido"),
        ("Escalation Rate", "Tasa de escalamiento"),
        ("Reassignment Rate", "Tasa de reasignación"),
        ("Avg Response", "Resp. media"),
        ("Avg Resolution", "Resolución media"),
        ("P90 Response", "Resp. P90"),
        ("Quantity", "Cantidad"),
        ("Trend", "tendencia"),
        ("Comparison", "Comparación"),
        ("Volume", "volumen"),
        ("World Map", "Mapa mundial"),
        ("Cumulative", "Acumulado"),
        ("Status", "Estado"),
        ("Department", "Departamento"),
        ("Top 10", "Top 10"),
        ("Top Reassignment", "Top reasignaciones"),
        ("Semi Gauge", "Indicador semicircular"),
        ("Jobs", "trabajos"),
        ("Response", "respuesta"),
        ("Resolution", "resolución"),
        ("Impact:", "Impacto:"),
        ("Resolution:", "Resolución:"),
        ("Shows", "Muestra"),
        ("Click", "Haga clic"),
        ("Average", "Promedio"),
        ("90th percentile", "percentil 90"),
    ],
    "zh-CN": [
        ("Corporate Dashboard", "企业仪表板"),
        ("OPS Dashboard", "OPS 仪表板"),
        ("GM Dashboard", "GM 仪表板"),
        ("Master Dashboard", "主仪表板"),
        ("Dashboard", "仪表板"),
        ("Switch:", "切换："),
        ("Filters", "筛选"),
        ("From:", "从："),
        ("To:", "到："),
        ("Apply", "应用"),
        ("Reset", "重置"),
        ("Toggle Dark/Light", "深色/浅色切换"),
        ("Language:", "语言："),
        ("Executive Analytics", "执行分析"),
        ("Job Order", "工单"),
        ("Created", "创建时间"),
        ("Resolution Min", "完成分钟"),
        ("SLA Breach Min", "SLA 违约分钟"),
        ("Export (PDF)", "导出（PDF）"),
        ("Loading dashboard...", "正在加载仪表板..."),
        ("Core Dashboard Charts", "核心仪表板图表"),
        ("KPI & Chart Dictionary", "KPI 与图表词典"),
        ("Top 20 JO", "JO 前 20"),
        ("All Hotels", "所有酒店"),
        ("All JO records", "全部 JO 记录"),
        ("NOTE", "备注"),
        ("FORMULA", "公式"),
        ("by week", "按周"),
        ("by Hotel", "按酒店"),
        ("Service Category", "服务类别"),
        ("Service Items", "服务项目"),
        ("Service Item", "服务项目"),
        ("Drilldown", "下钻"),
        ("Completion Rate", "完成率"),
        ("SLA Compliance", "SLA 合规率"),
        ("Timeout Rate", "超时率"),
        ("Escalation Rate", "升级率"),
        ("Reassignment Rate", "转派率"),
        ("Avg Response", "平均响应"),
        ("Avg Resolution", "平均完成"),
        ("P90 Response", "P90 响应"),
        ("Quantity", "数量"),
        ("Trend", "趋势"),
        ("Comparison", "比较"),
        ("Volume", "量"),
        ("World Map", "世界地图"),
        ("Cumulative", "累计"),
        ("Status", "状态"),
        ("Department", "部门"),
        ("Top 10", "前 10"),
        ("Top Reassignment", "转派前列"),
        ("Semi Gauge", "半圆仪表"),
        ("Jobs", "工单"),
        ("Response", "响应"),
        ("Resolution", "完成"),
        ("Impact:", "影响："),
        ("Resolution:", "解决："),
        ("Shows", "显示"),
        ("Click", "点击"),
        ("Average", "平均"),
        ("90th percentile", "第 90 百分位"),
    ],
    "zh-TW": [
        ("Corporate Dashboard", "企業儀表板"),
        ("OPS Dashboard", "OPS 儀表板"),
        ("GM Dashboard", "GM 儀表板"),
        ("Master Dashboard", "主儀表板"),
        ("Dashboard", "儀表板"),
        ("Switch:", "切換："),
        ("Filters", "篩選"),
        ("From:", "從："),
        ("To:", "到："),
        ("Apply", "套用"),
        ("Reset", "重設"),
        ("Toggle Dark/Light", "深色/淺色切換"),
        ("Language:", "語言："),
        ("Executive Analytics", "執行分析"),
        ("Job Order", "工單"),
        ("Created", "建立時間"),
        ("Resolution Min", "完成分鐘"),
        ("SLA Breach Min", "SLA 違約分鐘"),
        ("Export (PDF)", "匯出（PDF）"),
        ("Loading dashboard...", "正在載入儀表板..."),
        ("Core Dashboard Charts", "核心儀表板圖表"),
        ("KPI & Chart Dictionary", "KPI 與圖表詞典"),
        ("Top 20 JO", "JO 前 20"),
        ("All Hotels", "所有酒店"),
        ("All JO records", "全部 JO 記錄"),
        ("NOTE", "備註"),
        ("FORMULA", "公式"),
        ("by week", "按週"),
        ("by Hotel", "按酒店"),
        ("Service Category", "服務類別"),
        ("Service Items", "服務項目"),
        ("Service Item", "服務項目"),
        ("Drilldown", "下鑽"),
        ("Completion Rate", "完成率"),
        ("SLA Compliance", "SLA 合規率"),
        ("Timeout Rate", "逾時率"),
        ("Escalation Rate", "升級率"),
        ("Reassignment Rate", "轉派率"),
        ("Avg Response", "平均回應"),
        ("Avg Resolution", "平均完成"),
        ("P90 Response", "P90 回應"),
        ("Quantity", "數量"),
        ("Trend", "趨勢"),
        ("Comparison", "比較"),
        ("Volume", "量"),
        ("World Map", "世界地圖"),
        ("Cumulative", "累計"),
        ("Status", "狀態"),
        ("Department", "部門"),
        ("Top 10", "前 10"),
        ("Top Reassignment", "轉派前列"),
        ("Semi Gauge", "半圓儀表"),
        ("Jobs", "工單"),
        ("Response", "回應"),
        ("Resolution", "完成"),
        ("Impact:", "影響："),
        ("Resolution:", "解決："),
        ("Shows", "顯示"),
        ("Click", "點擊"),
        ("Average", "平均"),
        ("90th percentile", "第 90 百分位"),
    ],
    "ja": [
        ("Corporate Dashboard", "コーポレートダッシュボード"),
        ("OPS Dashboard", "OPS ダッシュボード"),
        ("GM Dashboard", "GM ダッシュボード"),
        ("Master Dashboard", "マスターダッシュボード"),
        ("Dashboard", "ダッシュボード"),
        ("Switch:", "切替:"),
        ("Filters", "フィルター"),
        ("From:", "開始:"),
        ("To:", "終了:"),
        ("Apply", "適用"),
        ("Reset", "リセット"),
        ("Toggle Dark/Light", "ダーク/ライト切替"),
        ("Language:", "言語:"),
        ("Executive Analytics", "エグゼクティブ分析"),
        ("Job Order", "作業指示"),
        ("Created", "作成日時"),
        ("Resolution Min", "完了分"),
        ("SLA Breach Min", "SLA 逸脱分"),
        ("Export (PDF)", "PDF出力"),
        ("Loading dashboard...", "ダッシュボードを読み込み中..."),
        ("Core Dashboard Charts", "コアダッシュボードチャート"),
        ("KPI & Chart Dictionary", "KPI・チャート辞書"),
        ("Top 20 JO", "JO 上位20"),
        ("All Hotels", "すべてのホテル"),
        ("All JO records", "すべての JO レコード"),
        ("NOTE", "メモ"),
        ("FORMULA", "式"),
        ("by week", "週次"),
        ("by Hotel", "ホテル別"),
        ("Service Category", "サービスカテゴリ"),
        ("Service Items", "サービス項目"),
        ("Service Item", "サービス項目"),
        ("Drilldown", "ドリルダウン"),
        ("Completion Rate", "完了率"),
        ("SLA Compliance", "SLA 遵守率"),
        ("Timeout Rate", "タイムアウト率"),
        ("Escalation Rate", "エスカレーション率"),
        ("Reassignment Rate", "再割り当て率"),
        ("Avg Response", "平均応答"),
        ("Avg Resolution", "平均完了"),
        ("P90 Response", "P90 応答"),
        ("Quantity", "数量"),
        ("Trend", "推移"),
        ("Comparison", "比較"),
        ("Volume", "量"),
        ("World Map", "世界地図"),
        ("Cumulative", "累計"),
        ("Status", "ステータス"),
        ("Department", "部門"),
        ("Top 10", "上位10"),
        ("Top Reassignment", "再割り当て上位"),
        ("Semi Gauge", "セミゲージ"),
        ("Jobs", "ジョブ"),
        ("Response", "応答"),
        ("Resolution", "完了"),
        ("Impact:", "影響:"),
        ("Resolution:", "対応:"),
        ("Shows", "表示"),
        ("Click", "クリック"),
        ("Average", "平均"),
        ("90th percentile", "90パーセンタイル"),
    ],
    "ko": [
        ("Corporate Dashboard", "법인 대시보드"),
        ("OPS Dashboard", "OPS 대시보드"),
        ("GM Dashboard", "GM 대시보드"),
        ("Master Dashboard", "마스터 대시보드"),
        ("Dashboard", "대시보드"),
        ("Switch:", "전환:"),
        ("Filters", "필터"),
        ("From:", "시작:"),
        ("To:", "종료:"),
        ("Apply", "적용"),
        ("Reset", "초기화"),
        ("Toggle Dark/Light", "다크/라이트 전환"),
        ("Language:", "언어:"),
        ("Executive Analytics", "경영 분석"),
        ("Job Order", "작업 지시"),
        ("Created", "생성일"),
        ("Resolution Min", "완료 분"),
        ("SLA Breach Min", "SLA 위반 분"),
        ("Export (PDF)", "PDF 내보내기"),
        ("Loading dashboard...", "대시보드 로딩 중..."),
        ("Core Dashboard Charts", "핵심 대시보드 차트"),
        ("KPI & Chart Dictionary", "KPI 및 차트 사전"),
        ("Top 20 JO", "JO 상위 20"),
        ("All Hotels", "모든 호텔"),
        ("All JO records", "모든 JO 기록"),
        ("NOTE", "메모"),
        ("FORMULA", "수식"),
        ("by week", "주간"),
        ("by Hotel", "호텔별"),
        ("Service Category", "서비스 카테고리"),
        ("Service Items", "서비스 항목"),
        ("Service Item", "서비스 항목"),
        ("Drilldown", "드릴다운"),
        ("Completion Rate", "완료율"),
        ("SLA Compliance", "SLA 준수율"),
        ("Timeout Rate", "타임아웃율"),
        ("Escalation Rate", "에스컬레이션율"),
        ("Reassignment Rate", "재할당율"),
        ("Avg Response", "평균 응답"),
        ("Avg Resolution", "평균 완료"),
        ("P90 Response", "P90 응답"),
        ("Quantity", "수량"),
        ("Trend", "추세"),
        ("Comparison", "비교"),
        ("Volume", "볼륨"),
        ("World Map", "세계 지도"),
        ("Cumulative", "누적"),
        ("Status", "상태"),
        ("Department", "부서"),
        ("Top 10", "상위 10"),
        ("Top Reassignment", "재할당 상위"),
        ("Semi Gauge", "세미 게이지"),
        ("Jobs", "작업"),
        ("Response", "응답"),
        ("Resolution", "완료"),
        ("Impact:", "영향:"),
        ("Resolution:", "해결:"),
        ("Shows", "표시"),
        ("Click", "클릭"),
        ("Average", "평균"),
        ("90th percentile", "90퍼센타일"),
    ],
    "th": [
        ("Corporate Dashboard", "แดชบอร์ดองค์กร"),
        ("OPS Dashboard", "แดชบอร์ด OPS"),
        ("GM Dashboard", "แดชบอร์ด GM"),
        ("Master Dashboard", "แดชบอร์ดหลัก"),
        ("Dashboard", "แดชบอร์ด"),
        ("Switch:", "สลับ:"),
        ("Filters", "ตัวกรอง"),
        ("From:", "จาก:"),
        ("To:", "ถึง:"),
        ("Apply", "ใช้"),
        ("Reset", "รีเซ็ต"),
        ("Toggle Dark/Light", "สลับมืด/สว่าง"),
        ("Language:", "ภาษา:"),
        ("Executive Analytics", "การวิเคราะห์เชิงผู้บริหาร"),
        ("Job Order", "ใบงาน"),
        ("Created", "วันที่สร้าง"),
        ("Resolution Min", "นาทีปิดงาน"),
        ("SLA Breach Min", "นาทีละเมิด SLA"),
        ("Export (PDF)", "ส่งออก (PDF)"),
        ("Loading dashboard...", "กำลังโหลดแดชบอร์ด..."),
        ("Core Dashboard Charts", "กราฟหลักของแดชบอร์ด"),
        ("KPI & Chart Dictionary", "พจนานุกรม KPI และกราฟ"),
        ("Top 20 JO", "JO 20 อันดับแรก"),
        ("All Hotels", "โรงแรมทั้งหมด"),
        ("All JO records", "บันทึก JO ทั้งหมด"),
        ("NOTE", "หมายเหตุ"),
        ("FORMULA", "สูตร"),
        ("by week", "รายสัปดาห์"),
        ("by Hotel", "ตามโรงแรม"),
        ("Service Category", "หมวดบริการ"),
        ("Service Items", "รายการบริการ"),
        ("Service Item", "รายการบริการ"),
        ("Drilldown", "เจาะลึก"),
        ("Completion Rate", "อัตราสำเร็จ"),
        ("SLA Compliance", "การปฏิบัติตาม SLA"),
        ("Timeout Rate", "อัตราหมดเวลา"),
        ("Escalation Rate", "อัตรายกระดับ"),
        ("Reassignment Rate", "อัตรามอบหมายใหม่"),
        ("Avg Response", "เวลาเฉลี่ยตอบกลับ"),
        ("Avg Resolution", "เวลาเฉลี่ยปิดงาน"),
        ("P90 Response", "P90 การตอบกลับ"),
        ("Quantity", "ปริมาณ"),
        ("Trend", "แนวโน้ม"),
        ("Comparison", "เปรียบเทียบ"),
        ("Volume", "ปริมาณ"),
        ("World Map", "แผนที่โลก"),
        ("Cumulative", "สะสม"),
        ("Status", "สถานะ"),
        ("Department", "แผนก"),
        ("Top 10", "10 อันดับแรก"),
        ("Top Reassignment", "การมอบหมายใหม่สูงสุด"),
        ("Semi Gauge", "เกจครึ่งวงกลม"),
        ("Jobs", "งาน"),
        ("Response", "ตอบกลับ"),
        ("Resolution", "ปิดงาน"),
        ("Impact:", "ผลกระทบ:"),
        ("Resolution:", "วิธีแก้ไข:"),
        ("Shows", "แสดง"),
        ("Click", "คลิก"),
        ("Average", "เฉลี่ย"),
        ("90th percentile", "เปอร์เซ็นไทล์ที่ 90"),
    ],
    "vi": [
        ("Corporate Dashboard", "Bảng điều khiển doanh nghiệp"),
        ("OPS Dashboard", "Bảng điều khiển OPS"),
        ("GM Dashboard", "Bảng điều khiển GM"),
        ("Master Dashboard", "Bảng điều khiển chính"),
        ("Dashboard", "bảng điều khiển"),
        ("Switch:", "Chuyển:"),
        ("Filters", "Bộ lọc"),
        ("From:", "Từ:"),
        ("To:", "Đến:"),
        ("Apply", "Áp dụng"),
        ("Reset", "Đặt lại"),
        ("Toggle Dark/Light", "Đổi tối/sáng"),
        ("Language:", "Ngôn ngữ:"),
        ("Executive Analytics", "Phân tích điều hành"),
        ("Job Order", "Lệnh công việc"),
        ("Created", "Ngày tạo"),
        ("Resolution Min", "Phút hoàn tất"),
        ("SLA Breach Min", "Phút vi phạm SLA"),
        ("Export (PDF)", "Xuất (PDF)"),
        ("Loading dashboard...", "Đang tải bảng điều khiển..."),
        ("Core Dashboard Charts", "Biểu đồ chính của bảng điều khiển"),
        ("KPI & Chart Dictionary", "Từ điển KPI và biểu đồ"),
        ("Top 20 JO", "Top 20 JO"),
        ("All Hotels", "Tất cả khách sạn"),
        ("All JO records", "Tất cả bản ghi JO"),
        ("NOTE", "GHI CHÚ"),
        ("FORMULA", "CÔNG THỨC"),
        ("by week", "theo tuần"),
        ("by Hotel", "theo khách sạn"),
        ("Service Category", "Danh mục dịch vụ"),
        ("Service Items", "mục dịch vụ"),
        ("Service Item", "mục dịch vụ"),
        ("Drilldown", "chi tiết"),
        ("Completion Rate", "Tỷ lệ hoàn thành"),
        ("SLA Compliance", "Tuân thủ SLA"),
        ("Timeout Rate", "Tỷ lệ hết thời gian"),
        ("Escalation Rate", "Tỷ lệ leo thang"),
        ("Reassignment Rate", "Tỷ lệ phân công lại"),
        ("Avg Response", "Phản hồi TB"),
        ("Avg Resolution", "Hoàn tất TB"),
        ("P90 Response", "P90 phản hồi"),
        ("Quantity", "số lượng"),
        ("Trend", "xu hướng"),
        ("Comparison", "so sánh"),
        ("Volume", "khối lượng"),
        ("World Map", "bản đồ thế giới"),
        ("Cumulative", "tích lũy"),
        ("Status", "trạng thái"),
        ("Department", "phòng ban"),
        ("Top 10", "Top 10"),
        ("Top Reassignment", "phân công lại cao nhất"),
        ("Semi Gauge", "đồng hồ bán nguyệt"),
        ("Jobs", "công việc"),
        ("Response", "phản hồi"),
        ("Resolution", "hoàn tất"),
        ("Impact:", "Tác động:"),
        ("Resolution:", "Giải pháp:"),
        ("Shows", "Hiển thị"),
        ("Click", "Nhấp"),
        ("Average", "trung bình"),
        ("90th percentile", "phân vị 90"),
    ],
    "ms": [
        ("Corporate Dashboard", "Papan Pemuka Korporat"),
        ("OPS Dashboard", "Papan Pemuka OPS"),
        ("GM Dashboard", "Papan Pemuka GM"),
        ("Master Dashboard", "Papan Pemuka Utama"),
        ("Dashboard", "papan pemuka"),
        ("Switch:", "Tukar:"),
        ("Filters", "Penapis"),
        ("From:", "Dari:"),
        ("To:", "Ke:"),
        ("Apply", "Guna"),
        ("Reset", "Set semula"),
        ("Toggle Dark/Light", "Gelap/Cerah"),
        ("Language:", "Bahasa:"),
        ("Executive Analytics", "Analitik eksekutif"),
        ("Job Order", "Arahan kerja"),
        ("Created", "Dicipta"),
        ("Resolution Min", "Minit penyelesaian"),
        ("SLA Breach Min", "Minit pelanggaran SLA"),
        ("Export (PDF)", "Eksport (PDF)"),
        ("Loading dashboard...", "Memuatkan papan pemuka..."),
        ("Core Dashboard Charts", "Carta utama papan pemuka"),
        ("KPI & Chart Dictionary", "Kamus KPI dan carta"),
        ("Top 20 JO", "JO 20 teratas"),
        ("All Hotels", "Semua hotel"),
        ("All JO records", "Semua rekod JO"),
        ("NOTE", "NOTA"),
        ("FORMULA", "FORMULA"),
        ("by week", "mengikut minggu"),
        ("by Hotel", "mengikut hotel"),
        ("Service Category", "Kategori perkhidmatan"),
        ("Service Items", "item perkhidmatan"),
        ("Service Item", "item perkhidmatan"),
        ("Drilldown", "drilldown"),
        ("Completion Rate", "Kadar selesai"),
        ("SLA Compliance", "Pematuhan SLA"),
        ("Timeout Rate", "Kadar tamat masa"),
        ("Escalation Rate", "Kadar eskalasi"),
        ("Reassignment Rate", "Kadar penugasan semula"),
        ("Avg Response", "Respons purata"),
        ("Avg Resolution", "Penyelesaian purata"),
        ("P90 Response", "Respons P90"),
        ("Quantity", "kuantiti"),
        ("Trend", "trend"),
        ("Comparison", "perbandingan"),
        ("Volume", "volum"),
        ("World Map", "peta dunia"),
        ("Cumulative", "terkumpul"),
        ("Status", "status"),
        ("Department", "jabatan"),
        ("Top 10", "10 teratas"),
        ("Top Reassignment", "penugasan semula teratas"),
        ("Semi Gauge", "tolok separuh"),
        ("Jobs", "kerja"),
        ("Response", "respons"),
        ("Resolution", "penyelesaian"),
        ("Impact:", "Impak:"),
        ("Resolution:", "Penyelesaian:"),
        ("Shows", "Menunjukkan"),
        ("Click", "Klik"),
        ("Average", "purata"),
        ("90th percentile", "persentil ke-90"),
    ],
}


def main():
    labels = read_labels()
    for lang, rules in RULES.items():
        payload = {label: translate(label, rules) for label in labels}
        out = ROOT / f"{lang}_lang.json"
        out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Wrote {out.name} ({len(payload)} keys)")


if __name__ == "__main__":
    main()
